theme: jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-multiple-languages-plugin
languages: ["de", "en"]
repository: Chaostreff-Potsdam/rtc22
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: Reconnect to Chaos
description: 27.12.2022 - 30.12.20222
mail: "`rtc22-orga .วลง. ccc-p @.@ org`"
imprint: https://www.ccc-p.org/Impressum